### ISSUE TITLE
Add man page and html doc to rpm/deb packages

### ISSUE THREAD

**Issue by uggla** [bcornec/python-redfish#19]
Everything in the title.

**Comment by bcornec** [comment]
I do not see any file associated with tha pull request. Not sure it's normal, maybe because you're not completely in good shape again !!! Hope your health is improving.

**Comment by uggla** [comment]
:)

Normal this is not a pull request but an issue request. You work too late. ;)
The goal is to not forget to include the required dep and files in rpm/deb packages.
Everything was provided by #18, documentation can be generated using the make file (ex : make man, make html) into the doc directory.
As an example here is the pdflatex doc produced by sphinx. (need the full texlive bundle)
[python-redfish.pdf](https://github.com/bcornec/python-redfish/files/127664/python-redfish.pdf)

**Comment by bcornec** [comment]
I'm working on this integration.

For the deb package we always have the issue of lack of upstream deb python-tortilla.

**Comment by uggla** [comment]
Bruno, just a short comment to warn you that my next PR (probably today or tomorrow) will contain some modifications to setuptool config.
Despite it will not modify anything from the doc part. You will probably have to modify the spec file to catch template files and conf files.

Regarding the deb package, I'm pretty sure you know a debian/ubuntu packager that could create those packages. :)
By the way this is also the reason why I worked on the Pypi package, so debian/ubuntu users can install python-redfish using pip. This is not as good as using distribution packages but better than nothing.

Finally when all of this will be ready, I will write a documentation explaining how to install/use that.

**Comment by bcornec** [comment]
Commit 8f6d519a6270960b5d9cb6939c02bf17295c1095 adds support for documentation for rpm packages

**Comment by uggla** [comment]
I would not provide the .pdf as it need "build requires texlive-scheme-full" which is a log of pkgs.
Or maybe html and pdf will need a rpm doc pkg. This will be required by Fedora rules as large doc should be in a separate pkg.
Anyway that's no big deal for now, maybe we can just track that point in a ticket ?

**Comment by bcornec** [comment]
Have large build requires doesn't impact users of the package, just builders. We could just provide the single page html and a separate more complete doc package indeed (that's what I was doing for MondoRescue) That could be a good intermediate solution.

**Comment by bcornec** [comment]
My latest PR is bringing doc into the rpm. Please review.

**Comment by bcornec** [comment]
Work is done for RPM based distros. For deb based it will be automatically done when deb packages are generated Cf: #55
