### ISSUE TITLE
Get PBVER from pbr

### ISSUE THREAD

**Issue by uggla** [bcornec/python-redfish#20]
Hello,

pbr is an openstack module to get revision, authors, changelog from git.
That will be cool to use this to set PBVER as well. Bruno do you thing we can do that ?

**Comment by bcornec** [comment]
I don't want to have OpenStack dependencies inside python-redfish, in order to keep it independant and easy to integrate in other projects.

PBVER is set externally to the project in a conf file. Same for PBREV (packaging notion).

However, it should not prevent python-redfish to be built locally without pb as well. To be discussed more I think.

**Comment by uggla** [comment]
Maybe my latest comments was a bit short. Pbr is not an openstack component. This is a tool to simplify the build process created by openstack team. By the way it is already part of our dependencies. (I removed it but you added it again :) )
All revision info are inside git and can be extracted from it and that's the goal of pbr.
This mechanism is used by setuptool to "create Pypi package", to my mind we could extend it to have a uniform revision number.
My point with this thread is to not have a "static" revision number within a conf file.
We could extend pb with pbr (plugin), so it will set the PBVER from git info. (Pbr is looking at git revision tag and commit to defined the build number, more info : http://docs.openstack.org/developer/pbr/)
I guess that could be a great enhancement to pb, because you will not have to worried about revision number. I also thing that implementing this into pbr should be not too complex.

**Comment by bcornec** [comment]
Revision inside git are the one associated to git, not necessarily the one you want for your project. 
E.g. when I'm building a package for the upcoming 0.3 release, how does git know that ? In fact it doesn't. Human knows, but not the tool. That's where you need to code that in a conf file to extract it from it, as you can't relay on git for that. I need to look a pbr to see whether we can use it that way or not.
The version number has to be put somewhere, and indeed be static there, but in a single place.
No pb to extend pb with pbr support, but I don't think it solves anything in that case.

Getting AUTHORS and ChangeLog is fine (but today pb also requires a changelog to be managed for multiple reasons - again something to study).

**Comment by uggla** [comment]
Maybe I should start by that, an example.
Pbr is using some kind of rules.
It takes the revision tag value (set by human)  then it increment based on the commit.
So today I have 0.2.1dev52 as pbr revision. Because we have tag 0.2 and I guess 52 commit from 0.2 up to now.
So as soon as you will tag 0.3, it will be taken into account and revision will become something like 0.3.1.
Of course it means that tag value into git should be coherent with project revision. But that's almost always the case, or at least a good practice.
The revision is specified at one place into git using tag. So there is no need to maintain an external conf file in parallel to specify revision.
By the way this is convenient for building, as you just have to checkout the corresponding release and launch the build process.
I know you are hard to convinced (you have no idea, hopefully I'm not your son :) ) but I think it is a good idea and useful for project management in general, I mean that could also serve you for mondo and pb.

**Comment by bcornec** [comment]
project-builder.org has now an option to support pbr managed sources, and use sdist to build the correct tar ball which is now standalone. Fixed after pb rev 2079, will be in next pb version.
Tested successfully with post 0.3 versions.
