### ISSUE TITLE
Having a .redfish directory in our home

### ISSUE THREAD

**Issue by bcornec** [bcornec/python-redfish#40]
We should create a directory in the home directory of the user, called .redfish, which could then host the log file that the tools will create (they should be kept separate between users, and shouldn't require root access or complex ownership setup under /var/log).

That directory could also host the config file then that we could call just ... config (instead of ~/.redfish.conf. But due to its nature, it would even be better to call it inventory.

This should also help solving #39

**Comment by bcornec** [comment]
CF #41

**Comment by uggla** [comment]
I agree #39 and #40. :+1: 
But the PR need to be refined mainly to check and exit properly if the user choose another location that could not be allowed (rights issue, etc...)

**Comment by bcornec** [comment]
Fixed with ce55371
