### ISSUE TITLE
Create a submodule for OEM stuff.

### ISSUE THREAD

**Issue by uggla** [bcornec/python-redfish#46]
Not in a hurry, but will be helpful to identified standard redfish part and OEM.
Despite we are not parsing OEM data right now, I think we will have to do it.

**Comment by bcornec** [comment]
Is it in the goal of the project ? Risk of duplicating manufacturer tools ?

**Comment by bcornec** [comment]
However our Bios implementation should be moved there for now.

**Comment by uggla** [comment]
Right, this part needs to be reviewed.
Also the bios part is not discovered from redfish links.
We need to test again this part, because it was not fully tested recently.

**Comment by uggla** [comment]
Done in #78.
